Lottery.WebMvc/Lottery.WebMvc/Controllers/PhonebookController.cs
using Lottery.DoMain.Constant;
using Lottery.DoMain.Models;
using Lottery.WebMvc.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lottery.WebMvc.Controllers
{
    public class PhonebookController : BaseController
    {
        public ActionResult ListPlayer()
        {
            return View();
        }
        public ActionResult CreatePlayer()
        {
            return View();
        }
        public ActionResult UpdatePlayer(int playerId)
        {
            var userData = GetCurrentUser();
            List<Phonebook> phonebooks = new List<Phonebook>();
            var dataBase = provider.GetAsync<List<Phonebook>>(string.Format(ApiUri.Get_Phonebook + "/{0}", userData.Id));
            if (dataBase != null && dataBase.Result != null && dataBase.Result.Data != null)
            {
                phonebooks = dataBase.Result.Data;
            }
            var phonebook = phonebooks.FirstOrDefault(x => x.Id == playerId);

            return View(phonebook);
        }

        [HttpPost]
        public ActionResult ExecuteCreatePlayer(string playerJsons)
        {
            var userData = GetCurrentUser();
            var players = JsonConvert.DeserializeObject<List<PhonebookModel>>(playerJsons);
            players[0].UserID = userData.Id;
            // Tạo mới
            if (players[0].Id == null)
            {
                players[0].IsDeleted = false;
                players[0].PhoneNumber = "";
                var playerBase = provider.PutAsync<object>(ApiUri.POST_UserUpdatePhonebook, players);
                if (playerBase != null || playerBase.Result != null || playerBase.Result.IsSuccessful)
                {
                    return Json(Success_Request(playerBase.Result.IsSuccessful));
                }
            }
            // Update
            else if (players[0].Id != null && !players[0].IsDeleted)
            {
                if (string.IsNullOrEmpty(players[0].PhoneNumber))
                {
                    players[0].PhoneNumber = "";
                }
                var playerBase = provider.PutAsync<object>(ApiUri.POST_UserUpdatePhonebook, players);
                if (playerBase != null || playerBase.Result != null || playerBase.Result.IsSuccessful)
                {
                    return Json(Success_Request(playerBase.Result.IsSuccessful));
                }
            }
            
            return View(Server_Error());

        }
        [HttpPost]
        public ActionResult ExecuteDeletePlayer(int playerId)
        {
            var userData = GetCurrentUser();
            List<Phonebook> phonebooks = new List<Phonebook>();
            var dataBase = provider.GetAsync<List<Phonebook>>(string.Format(ApiUri.Get_Phonebook + "/{0}", userData.Id));
            if (dataBase != null && dataBase.Result != null && dataBase.Result.Data != null)
            {
                phonebooks = dataBase.Result.Data;
            }
            var phonebook = phonebooks.FirstOrDefault(x => x.Id == playerId);
            phonebook.IsDeleted = true;
            var players = new List<Phonebook>();
            players.Add(phonebook);

            // Xóa
            var playerBase = provider.PutAsync<object>(ApiUri.POST_UserUpdatePhonebook, players);
            if (playerBase != null || playerBase.Result != null || playerBase.Result.IsSuccessful)
            {
                return Json(Success_Request(playerBase.Result.IsSuccessful));
            }

            return View(Server_Error());
        }
    }
}

Lottery.WebMvc/Lottery.WebMvc/Views/Phonebook/CreatePlayer.cshtml
@using Lottery.DoMain.Constant;
@using Lottery.DoMain.Models;
@using Newtonsoft.Json;
@using Lottery.DoMain.Enum;
@{
    Layout = "~/Views/Shared/_Layout.cshtml";

    FormsIdentity id = (FormsIdentity)HttpContext.Current.User.Identity;
    FormsAuthenticationTicket ticket = id.Ticket;
    var userData = JsonConvert.DeserializeObject<User>(ticket.UserData);

}

<!DOCTYPE html>
<!-- Created By CodingLab - www.codinglabweb.com -->
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <link href="~/assets/css/createPlayer.css" rel="stylesheet" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login Form | CodingLab</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css" />
</head>
<body>
    <div class="container">
        <div class="wrapper">
            <div class="title"><span>Thêm mới</span></div>
            <form id="createPlayerForm" action="#">
                <div class="row">
                    <i class="fas fa-user"></i>
                    <input name="name" type="text" placeholder="Tên người chơi" required>
                </div>
                @*<div class="row">
            <i class="fas fa-phone"></i>
            <input type="text" placeholder="Số điện thoại" required>
        </div>*@
                <div class="row">
                    <i class="fas fa-calculator"></i>
                    <input name="tileXac" type="number" step="any" placeholder="Tỷ lệ xác" required>
                </div>
                <div class="row">
                    <i class="fas fa-calculator"></i>
                    <input name="tileThuong" type="number" placeholder="Tỷ lệ thưởng" required>
                </div>
                <div class="row">
                    <i class="fas fa-calculator"></i>
                    <input name="tileBaSo" type="number" placeholder="Tỷ lệ ba càng" required>
                </div>
                <div class="row button">
                    <input type="submit" value="Đăng ký">
                </div>

                <div class="signup-link">Người chơi đã có trong danh bạ? <a href="/Calculation/IndexImport"> Trang tính!</a></div>

            </form>
        </div>
    </div>
    <script>
        // Bắt sự kiện submit của biểu mẫu
        document.getElementById("createPlayerForm").addEventListener("submit", function (event) {
            event.preventDefault(); // Ngăn chặn biểu mẫu gửi đi mặc định

            var playerModel = {
                name: document.getElementsByName("name")[0].value,
                tileXac: document.getElementsByName("tileXac")[0].value,
                tileThuong: document.getElementsByName("tileThuong")[0].value,
                tileBaSo: document.getElementsByName("tileBaSo")[0].value,
            }
            var playerModels = [playerModel];
            playerModels.push();
            ShowOverlay(true);
            playerJsons = JSON.stringify(playerModels);
            $.ajax({
                    type: "POST",
                    data:
                    {
                        "playerJsons": playerJsons,
                    },
                    url: "@Url.Action("ExecuteCreatePlayer", "Phonebook")",
                    success: function (data)
                    {
                        if (data.Success && data.Data) {
                            awesomeAlert({
                                header: true,
                                type: 'success',
                                title: 'Thành công!',
                                message: 'Tạo mới người chơi thành công.',
                                //bgColor: '#2dd284',
                                img: '/assets/images/icon/success.svg',
                                buttonOK: 'Xong!',
                                closeStyle: 'circle'
                            }).then(res => window.location = "/Phonebook/ListPlayer")
                        }
                        else {
                            var message = "Đã có lỗi xảy ra."
                            if (!isNullOrEmpty(data.Message)) {
                                message = data.Message;
                            }
                            awesomeAlert({
                                header: true,
                                type: 'error',
                                title: 'Có lỗi!',
                                message: message,
                                //bgColor: '#2dd284',
                                img: '/assets/images/icon/error.svg',
                                buttonOK: 'Oke!',
                                closeStyle: 'circle'
                            }).then(res => false)
                        }
                        hideOverlay();
                    },
                })
        });
    </script>
</body>
</html>

Lottery.WebMvc/Lottery.WebMvc/Views/Phonebook/UpdatePlayer.cshtml
@using Lottery.DoMain.Constant;
@using Newtonsoft.Json;
@using Lottery.DoMain.Enum;
@using Lottery.DoMain.Models;
@{
    Layout = "~/Views/Shared/_Layout.cshtml";

    FormsIdentity id = (FormsIdentity)HttpContext.Current.User.Identity;
    FormsAuthenticationTicket ticket = id.Ticket;
    var userData = JsonConvert.DeserializeObject<User>(ticket.UserData);

}
@model Phonebook
<!DOCTYPE html>
<!-- Created By CodingLab - www.codinglabweb.com -->
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <link href="~/assets/css/createPlayer.css" rel="stylesheet" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login Form | CodingLab</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css" />
</head>
<body>
    <div class="container">
        <div class="wrapper">
            <div class="title"><span>Cập nhật</span></div>
            @if (Model != null)
            {
                <form id="updatePlayerForm" action="#">
                    <div class="row">
                        <i class="fas fa-user"></i>
                        <input name="name" type="text" placeholder="Tên người chơi" value="@Model.Name" required>
                    </div>
                    @*<div class="row">
                    <i class="fas fa-phone"></i>
                    <input type="text" placeholder="Số điện thoại" required>
                </div>*@
                    <div class="row">
                        <i class="fas fa-calculator"></i>
                        <input name="tileXac" type="number" step="any" placeholder="Tỷ lệ xác" value="@Model.TileXac" required>
                    </div>
                    <div class="row">
                        <i class="fas fa-calculator"></i>
                        <input name="tileThuong" type="number" placeholder="Tỷ lệ thưởng" value="@Model.TileThuong" required>
                    </div>
                    <div class="row">
                        <i class="fas fa-calculator"></i>
                        <input name="tileBaSo" type="number" placeholder="Tỷ lệ ba càng" value="@Model.TileBaSo" required>
                    </div>
                    <div class="row button">
                        <input type="submit" value="Cập nhật">
                    </div>
                    
                    <div class="signup-link">Người chơi đã có trong danh bạ? <a href="/Calculation/IndexImport"> Trang tính!</a></div>

                </form>
            }
        </div>
    </div>
    <script>
        // Bắt sự kiện submit của biểu mẫu
        document.getElementById("updatePlayerForm").addEventListener("submit", function (event) {
            event.preventDefault(); // Ngăn chặn biểu mẫu gửi đi mặc định

            var playerModel = {
                id: @Model.Id,
                name: document.getElementsByName("name")[0].value,
                tileXac: document.getElementsByName("tileXac")[0].value,
                tileThuong: document.getElementsByName("tileThuong")[0].value,
                tileBaSo: document.getElementsByName("tileBaSo")[0].value,
            }
            var playerModels = [playerModel];
            playerModels.push();
            ShowOverlay(true);
            playerJsons = JSON.stringify(playerModels);
            $.ajax({
                    type: "POST",
                    data:
                    {
                        "playerJsons": playerJsons,
                    },
                    url: "@Url.Action("ExecuteCreatePlayer", "Phonebook")",
                    success: function (data)
                    {
                        if (data.Success && data.Data) {
                            awesomeAlert({
                                header: true,
                                type: 'success',
                                title: 'Thành công!',
                                message: 'Cập nhật người chơi thành công.',
                                //bgColor: '#2dd284',
                                img: '/assets/images/icon/success.svg',
                                buttonOK: 'Xong!',
                                closeStyle: 'circle'
                            }).then(res => window.location = "/Phonebook/ListPlayer")
                        }
                        else {
                            var message = "Đã có lỗi xảy ra."
                            if (!isNullOrEmpty(data.Message)) {
                                message = data.Message;
                            }
                            awesomeAlert({
                                header: true,
                                type: 'error',
                                title: 'Có lỗi!',
                                message: message,
                                //bgColor: '#2dd284',
                                img: '/assets/images/icon/error.svg',
                                buttonOK: 'Oke!',
                                closeStyle: 'circle'
                            }).then(res => false)
                        }
                        hideOverlay();
                    },
                })
        });
    </script>
</body>
</html>